version: '3.8'

services:
  anakonda:
    build:
      context: .
      dockerfile: ./srv/anaconda/Dockerfile
    container_name: anakonda
    volumes:
      - ./notebooks:/opt/notebooks
    ports:
      - '80:8888'
    command:
      /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root
    networks:
      - open-network
    tty: true

networks:
  open-network:
    name: open-network
    driver: bridge